name: dl
channels:
  - conda-forge
  - defaults
dependencies:
  - nb_conda_kernels=2.1.0=py36_0
  - _nb_ext_conf=0.4.0=py36_1
  - absl-py=0.2.2=py36_0
  - anaconda-client=1.6.14=py36_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.6.2=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h945400d_0
  - chardet=3.0.4=py36h420ce6e_1
  - clyent=1.2.2=py36hb10d595_1
  - colorama=0.3.9=py36h029ae33_0
  - cryptography=2.2.2=py36hfa6e2cd_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - freetype=2.8=h51f8f2c_1
  - gast=0.2.0=py36_0
  - grpcio=1.12.0=py36h1a1b453_0
  - h5py=2.8.0=py36h3bdd7fb_0
  - hdf5=1.10.2=hac2f561_1
  - html5lib=0.9999999=py36_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.6=py36h148d497_1
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36h292fed1_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36h6d89b47_1
  - jupyter_core=4.4.0=py36h56e9d50_0
  - keras=2.1.6=py36_0
  - kiwisolver=1.0.1=py36h12c3424_0
  - libpng=1.6.34=h79bbb47_0
  - libprotobuf=3.5.2=he0781b1_0
  - libsodium=1.0.16=h9d3ae62_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=2.6.11=py36_0
  - markupsafe=1.0=py36h0e26971_1
  - matplotlib=2.2.2=py36h153e9ff_1
  - mistune=0.8.3=py36hfa6e2cd_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h452e1ab_0
  - mkl_random=1.0.1=py36h9258bd6_0
  - msys2-conda-epoch=20160418=1
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.0=py36_0
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - nbpresent=3.0.2=py36_0
  - notebook=5.5.0=py36_0
  - numpy=1.14.3=py36h9fa60d3_2
  - numpy-base=1.14.3=py36h5c71026_2
  - openssl=1.0.2o=h8ea7d77_0
  - pandas=0.23.0=py36h830ac7b_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.2.1=py36_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pip=10.0.1=py36_0
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - protobuf=3.5.2=py36h6538335_0
  - pycparser=2.18=py36hd053e01_1
  - pygments=2.2.0=py36hb010967_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36h785a196_1
  - pyqt=5.9.2=py36h1aa27d4_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - pywinpty=0.5.3=py36_0
  - pyyaml=3.12=py36h1d1928f_1
  - pyzmq=17.0.0=py36hfa6e2cd_1
  - qt=5.9.6=vc14h62aca36_0
  - qtconsole=4.3.1=py36h99a29a9_0
  - requests=2.18.4=py36h4371aae_1
  - scikit-learn=0.19.1=py36h53aea1b_0
  - scipy=1.1.0=py36h672f292_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36h4db2310_1
  - sqlite=3.24.0=h7602738_0
  - tensorboard=1.8.0=py36he025d50_0
  - tensorflow=1.8.0=0
  - tensorflow-base=1.8.0=py36h1a1b453_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h096827d_0
  - urllib3=1.22=py36h276f60a_0
  - vc=14.1=h0510ff6_3
  - vs2015_runtime=15.5.2=3
  - wcwidth=0.1.7=py36h3d5aa90_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - win_inet_pton=1.0.1=py36he67d7fd_1
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=he025d50_1
  - zlib=1.2.11=h8395fce_2
  - pip:
    - astroid==1.6.5
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - pylint==1.9.2
    - wrapt==1.10.11
prefix: C:\ProgramData\Miniconda3\envs\dl

